chore: check lint fix

diff --git a/.github/workflows/bump.yml b/.github/workflows/bump.yml
--- a/.github/workflows/bump.yml
+++ b/.github/workflows/bump.yml
@@ -12,35 +12,35 @@ env:
   NODE_VERSION: 20
 
 jobs:
-  bump:
-    runs-on: ubuntu-latest
-    outputs:
-      version: ${{ steps.bump.outputs.version }}
-    steps:
-      - uses: sap/ai-sdk-js/.github/actions/setup@main
-        with:
-          token: ${{ secrets.GH_CLOUD_SDK_JS_ADMIN_WRITE_TOKEN }}
-          ref: 'main'
-      - name: bump version
-        uses: sap/cloud-sdk-js/.github/actions/changesets-fixed-version-bump@main
-        id: bump
-        with:
-          majorVersion: ${{ inputs.majorVersion }}
-      - name: merge and write Changelogs
-        id: merge-changelogs
-        uses: sap/cloud-sdk-js/.github/actions/merge-and-write-changelogs@main
-        env:
-          VERSION: ${{ steps.bump.outputs.version }}
-      - uses: sap/cloud-sdk-js/.github/actions/commit-and-tag@main
-        name: Commit and tag
-        with:
-          version: ${{ steps.bump.outputs.version }}
-          user-name: sap-ai-sdk
+  # bump:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     version: ${{ steps.bump.outputs.version }}
+  #   steps:
+  #     - uses: sap/ai-sdk-js/.github/actions/setup@main
+  #       with:
+  #         token: ${{ secrets.GH_CLOUD_SDK_JS_ADMIN_WRITE_TOKEN }}
+  #         ref: 'main'
+  #     - name: bump version
+  #       uses: sap/cloud-sdk-js/.github/actions/changesets-fixed-version-bump@main
+  #       id: bump
+  #       with:
+  #         majorVersion: ${{ inputs.majorVersion }}
+  #     - name: merge and write Changelogs
+  #       id: merge-changelogs
+  #       uses: sap/cloud-sdk-js/.github/actions/merge-and-write-changelogs@main
+  #       env:
+  #         VERSION: ${{ steps.bump.outputs.version }}
+  #     - uses: sap/cloud-sdk-js/.github/actions/commit-and-tag@main
+  #       name: Commit and tag
+  #       with:
+  #         version: ${{ steps.bump.outputs.version }}
+  #         user-name: sap-ai-sdk
 
   prepare-release-notes:
     name: Prepare Release Notes
     runs-on: ubuntu-latest
-    needs: [bump]
+    # needs: [bump]
     outputs:
       pr_url: ${{ steps.open_pr.outputs.pr_url }}
     steps:
@@ -65,35 +65,16 @@ jobs:
         run: |
           git config --local user.email "cloudsdk@sap.com"
           git config --local user.name "SAP Cloud SDK Bot"
-          BRANCH_NAME="update-release-notes-${{ needs.bump.outputs.version }}"
+          BRANCH_NAME="update-release-notes-1.12.0"
           git checkout -b "${BRANCH_NAME}"
+          pnpm lint:fix
           git add docs-js/release-notes.mdx
-          if git diff --staged --quiet; then
-            echo "No changes to commit."
-            # Output an empty pr_url if no changes
-            echo "pr_url=" >> "$GITHUB_OUTPUT"
-          else
-            git commit -m "update release notes" -a
-            git push -u origin "${BRANCH_NAME}"
 
-            echo ${{ secrets.BOT_SDK_JS_FOR_DOCS_REPO_PR }} | gh auth login --hostname github.com --with-token
-            gh config set prompt disabled
-            PR_BODY="Auto-created by update release notes workflow."
-            PR_TITLE="Update JS Release Notes"
-            PR_URL=$(gh pr create --head "${BRANCH_NAME}" --title "${PR_TITLE}" --body "${PR_BODY}")
-            echo "Release notes PR created: $PR_URL"
-            if [[ -n "$PR_URL" ]]; then
-              echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
-            else
-              echo "Failed to create PR or extract URL."
-              echo "pr_url=" >> "$GITHUB_OUTPUT"
-            fi
-          fi
 
   handle-failure:
     name: Handle Failure
     runs-on: ubuntu-latest
-    needs: [bump, prepare-release-notes]
+    needs: [prepare-release-notes]
     if: ${{ failure() }}
     permissions:
       contents: write
@@ -102,15 +83,15 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 1
-      - name: 'Delete Release Tag'
-        if: ${{ needs.bump.outputs.version != '' }}
-        run: |
-          TAG_NAME="v${{ needs.bump.outputs.version }}"
-          echo "Attempting to delete tag ${TAG_NAME}..."
-          git push --delete origin "${TAG_NAME}" || echo "Failed to delete tag ${TAG_NAME} (it might not exist)."
-        env:
-          GITHUB_TOKEN: ${{ secrets.GH_CLOUD_SDK_JS_ADMIN_WRITE_TOKEN }}
-          continue-on-error: true
+      # - name: 'Delete Release Tag'
+      #   if: ${{ needs.bump.outputs.version != '' }}
+      #   run: |
+      #     TAG_NAME="v${{ needs.bump.outputs.version }}"
+      #     echo "Attempting to delete tag ${TAG_NAME}..."
+      #     git push --delete origin "${TAG_NAME}" || echo "Failed to delete tag ${TAG_NAME} (it might not exist)."
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GH_CLOUD_SDK_JS_ADMIN_WRITE_TOKEN }}
+      #     continue-on-error: true
       - name: 'Close Release Notes PR and Delete Branch'
         if: ${{ needs.prepare-release-notes.outputs.pr_url != '' }}
         run: |
