chore: update scripts

diff --git a/.github/workflows/bump.yml b/.github/workflows/bump.yml
--- a/.github/workflows/bump.yml
+++ b/.github/workflows/bump.yml
@@ -12,38 +12,42 @@ env:
   NODE_VERSION: 20
 
 jobs:
-  # bump:
-  #   runs-on: ubuntu-latest
-  #   outputs:
-  #     version: ${{ steps.bump.outputs.version }}
-  #   steps:
-  #     - uses: sap/ai-sdk-js/.github/actions/setup@main
-  #       with:
-  #         token: ${{ secrets.GH_CLOUD_SDK_JS_ADMIN_WRITE_TOKEN }}
-  #         ref: 'main'
-  #     - name: bump version
-  #       uses: sap/cloud-sdk-js/.github/actions/changesets-fixed-version-bump@main
-  #       id: bump
-  #       with:
-  #         majorVersion: ${{ inputs.majorVersion }}
-  #     - name: merge and write Changelogs
-  #       id: merge-changelogs
-  #       uses: sap/cloud-sdk-js/.github/actions/merge-and-write-changelogs@main
-  #       env:
-  #         VERSION: ${{ steps.bump.outputs.version }}
-  #     - uses: sap/cloud-sdk-js/.github/actions/commit-and-tag@main
-  #       name: Commit and tag
-  #       with:
-  #         version: ${{ steps.bump.outputs.version }}
-  #         user-name: sap-ai-sdk
+  bump:
+    runs-on: ubuntu-latest
+    outputs:
+      version: ${{ steps.bump.outputs.version }}
+    steps:
+      - uses: sap/ai-sdk-js/.github/actions/setup@main
+        with:
+          token: ${{ secrets.GH_CLOUD_SDK_JS_ADMIN_WRITE_TOKEN }}
+          ref: 'main'
+      - name: bump version
+        uses: sap/cloud-sdk-js/.github/actions/changesets-fixed-version-bump@main
+        id: bump
+        with:
+          majorVersion: ${{ inputs.majorVersion }}
+      - name: merge and write Changelogs
+        id: merge-changelogs
+        uses: sap/cloud-sdk-js/.github/actions/merge-and-write-changelogs@main
+        env:
+          VERSION: ${{ steps.bump.outputs.version }}
+      - uses: sap/cloud-sdk-js/.github/actions/commit-and-tag@main
+        name: Commit and tag
+        with:
+          version: ${{ steps.bump.outputs.version }}
+          user-name: sap-ai-sdk
 
   prepare-release-notes:
     name: Prepare Release Notes
     runs-on: ubuntu-latest
-    # needs: [bump]
+    needs: [bump]
     outputs:
       pr_url: ${{ steps.open_pr.outputs.pr_url }}
     steps:
+      - name: Checkout current repository
+        uses: sap/ai-sdk-js/.github/actions/setup@main
+        with:
+          node-version: ${{ env.NODE_VERSION }}
       - name: Checkout Docs Repo
         uses: actions/checkout@v4
         with:
@@ -53,25 +57,44 @@ jobs:
           fetch-depth: 0
       - name: Update release notes file
         id: update-notes
-        working-directory: ${{ env.DOCS_CHECKOUT_PATH }}
         run: |
-          npm ci
-          NODE_OPTIONS="--loader ts-node/esm" npm ts-node --esm scripts/execute-add-changelog.ts
+          pnpm node --loader ts-node/esm scripts/execute-add-changelog.ts
       - name: Open Release notes PR
         id: open_pr
         working-directory: ${{ env.DOCS_CHECKOUT_PATH }}
         run: |
           git config --local user.email "cloudsdk@sap.com"
           git config --local user.name "SAP Cloud SDK Bot"
-          BRANCH_NAME="update-release-notes-1.12.0"
+          BRANCH_NAME="update-release-notes-js-${{ needs.bump.outputs.version }}"
           git checkout -b "${BRANCH_NAME}"
-          npm run lint:fix
           git add docs-js/release-notes.mdx
+          # if git diff --staged --quiet; then
+          #   echo "No changes to commit."
+          #   # Output an empty pr_url if no changes
+          #   echo "pr_url=" >> "$GITHUB_OUTPUT"
+          # else
+          #   git commit -m "update release notes" -a
+          #   git push -u origin "${BRANCH_NAME}"
+
+          #   gh config set prompt disabled
+          #   PR_BODY="Auto-created by update release notes workflow."
+          #   PR_TITLE="Update JS Release Notes"
+          #   PR_URL=$(gh pr create --head "${BRANCH_NAME}" --title "${PR_TITLE}" --body "${PR_BODY}")
+          #   echo "Release notes PR created: $PR_URL"
+          #   if [[ -n "$PR_URL" ]]; then
+          #     echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
+          #   else
+          #     echo "Failed to create PR or extract URL."
+          #     echo "pr_url=" >> "$GITHUB_OUTPUT"
+          #   fi
+          # fi
+          env:
+            GH_TOKEN: ${{ secrets.BOT_SDK_JS_FOR_DOCS_REPO_PR }}
 
   handle-failure:
     name: Handle Failure
     runs-on: ubuntu-latest
-    needs: [prepare-release-notes]
+    needs: [bump, prepare-release-notes]
     if: ${{ failure() }}
     permissions:
       contents: write
@@ -80,15 +103,15 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 1
-      # - name: 'Delete Release Tag'
-      #   if: ${{ needs.bump.outputs.version != '' }}
-      #   run: |
-      #     TAG_NAME="v${{ needs.bump.outputs.version }}"
-      #     echo "Attempting to delete tag ${TAG_NAME}..."
-      #     git push --delete origin "${TAG_NAME}" || echo "Failed to delete tag ${TAG_NAME} (it might not exist)."
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GH_CLOUD_SDK_JS_ADMIN_WRITE_TOKEN }}
-      #     continue-on-error: true
+      - name: 'Delete Release Tag'
+        if: ${{ needs.bump.outputs.version != '' }}
+        run: |
+          TAG_NAME="v${{ needs.bump.outputs.version }}"
+          echo "Attempting to delete tag ${TAG_NAME}..."
+          git push --delete origin "${TAG_NAME}" || echo "Failed to delete tag ${TAG_NAME} (it might not exist)."
+        env:
+          GH_TOKEN: ${{ secrets.GH_CLOUD_SDK_JS_ADMIN_WRITE_TOKEN }}
+          continue-on-error: true
       - name: 'Close Release Notes PR and Delete Branch'
         if: ${{ needs.prepare-release-notes.outputs.pr_url != '' }}
         run: |
